services:
  registry:
    build: .
    image: nanopub/registry
    restart: unless-stopped
    environment:
      JPDA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    ports:
      - 9292:8080
      - 5005:5005
    volumes:
      - ./setting.trig:/data/setting.trig
    entrypoint: 'catalina.sh jpda run'
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  mongodb:
    image: mongo:7
    restart: unless-stopped
    # entrypoint solution adjusted from here: https://stackoverflow.com/a/75572007
    entrypoint: >
      /bin/bash -c '
      echo "rs.initiate()" > /docker-entrypoint-initdb.d/1-init-replicaset.js &&
      /usr/local/bin/docker-entrypoint.sh mongod --replSet rs0 --bind_ip_all --noauth'
    volumes:
      - ./data/mongodb:/data/db
    logging:
      options:
        max-size: "10m"
        max-file: "3"
