services:
  registry:
    build: .
    image: nanopub/registry
    restart: unless-stopped
    ports:
      - 9292:8080
    volumes:
      - ./setting.trig:/data/setting.trig
  mongodb:
    image: mongo:7
    restart: unless-stopped
    # entrypoint solution from here: https://stackoverflow.com/a/75572007
    entrypoint: >
      /bin/bash -c '
      echo "rs.initiate()" > /docker-entrypoint-initdb.d/1-init-replicaset.js &&
      echo "db = db.getSiblingDB(process.env[$0]);" > /docker-entrypoint-initdb.d/2-init-db-collection.js &&
      echo "db.createCollection($1, { capped: false });" >> /docker-entrypoint-initdb.d/2-init-db-collection.js &&
      echo "db.init.insert([{ message: $2 }]);" >> /docker-entrypoint-initdb.d/2-init-db-collection.js &&
      /usr/local/bin/docker-entrypoint.sh mongod --replSet rs0 --bind_ip_all --noauth' "'MONGO_APP_DATABASE'" "'init'" "'db initialized successfully'"
    volumes:
      - ./data/mongodb:/data/db
