version: '2'
services:
  registry:
    build: .
    #image: nanopub/registry
    restart: unless-stopped
    ports:
      - 9292:8080
  db:
    image: nanopub/mongo
    #image: mongo
    restart: unless-stopped
    volumes:
      - ./data/mongodb:/data/db
